from django.core.mail import EmailMessage


def welcome_email(user):
    message_title = f"Hello {user.name}, thank you for registering to Emailnder!"
    message_body = f"""
Hello {user.name}!
Your account has been created sucesfully.
Now you can log in and start adding your remainders.

That message has been automatically generated by Emailnder.
"""

    return EmailMessage(message_title, message_body, to=[user.email])
