# Generated by Django 4.0.10 on 2024-07-24 15:42

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reminder_date', models.DateField(validators=[core.validators.validate_reminder_date])),
                ('permanent', models.BooleanField(default=False)),
                ('sent_check', models.CharField(choices=[('None', 'None'), ('month', 'Month'), ('week', 'Week'), ('three_days', 'Three Days'), ('one_day', 'One Day'), ('today', 'Today')], default='None', max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
