# Generated by Django 4.0.10 on 2024-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remainder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='sent_check',
            field=models.CharField(choices=[('None', 'None'), ('month', 'Month'), ('week', 'Week'), ('three_days', 'Three Days'), ('one_day', 'One Day'), ('today', 'Today')], default='None', max_length=255),
        ),
    ]
